import { redirect } from 'next/navigation';

/** Legacy iframe/print entry point. Catalogs are now generated by the worker. */
export default function LegacyCatalogPrintPage() {
  redirect('/dashboard/e-katalog');
}
